### ISSUE TITLE
Integrate form validator

### ISSUE THREAD

**Issue by webknjaz** [GDG-Ukraine/gdg.org.ua#29]
https://github.com/Deepwalker/trafaret

And/or `wtform-alchemy`.

**Comment by webknjaz** [comment]
or https://cerberus.readthedocs.org/en/latest/

**Comment by anxolerd** [comment]
Any requirements for it?

**Comment by webknjaz** [comment]
It's not about DB schemas. It's about data validation on input.

Yet another example of validation framework is LIVR by WebbyLab (you saw speech of its CTO @ KyivJS)
http://livr-spec.org/

**Comment by anxolerd** [comment]
## Problem:
It is unclear, why user's response cannot be saved. Hence user may spend a lot of time trying to register to event without any success because he entered too many symbols in some field
_for example, I spent 5 minutes trying to submit form with *National Technical University Of Ukraine "Kyiv Polytechnic Institute"* in the `Company` field_

## Todo:
Integrate some form validation in order to validate user input before trying to save it to the database. Validator should also return an error message if error happened.

/cc @webknjaz if there is some `critical` label, please add it to this issue

**Comment by webknjaz** [comment]
@anxolerd I've enabled wrapping http errors into JSON for REST API. You may use this possibility.
